# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0002_auto_20170811_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='datetime',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='date',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='Description',
            new_name='description',
        ),
    ]
