# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0004_auto_20170812_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='facility',
            name='block',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MySite.Block'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MySite.Complex'),
        ),
        migrations.AddField(
            model_name='unit',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MySite.Block'),
        ),
    ]
