# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0005_auto_20170813_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
