# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0006_auto_20170824_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='cost',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
