# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MySite', '0001_initial'),
        ('MyUser', '0003_auto_20170825_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PayByAccount',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Resident.Account')),
            ],
        ),
        migrations.CreateModel(
            name='PayByBank',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cost', models.IntegerField(null=True)),
                ('event_cost', models.IntegerField(null=True)),
                ('facility_cost', models.IntegerField(null=True)),
                ('common_bills_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('reserve_date', models.DateTimeField(primary_key=True, serialize=False)),
                ('use_finishDate', models.DateTimeField()),
                ('use_startDate', models.DateTimeField()),
                ('cost', models.IntegerField()),
                ('state', models.CharField(choices=[('A', 'تایید شده'), ('NC', 'بررسی نشده'), ('R', 'رد شده')], max_length=2)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MySite.Facility')),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_count', models.IntegerField()),
                ('car_count', models.IntegerField()),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MyUser.Member')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MySite.Unit')),
            ],
        ),
        migrations.AddField(
            model_name='reserve',
            name='resident',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Resident.Resident'),
        ),
        migrations.AddField(
            model_name='paybybank',
            name='receipt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Resident.Receipt'),
        ),
        migrations.AddField(
            model_name='paybybank',
            name='resident',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Resident.Resident'),
        ),
        migrations.AddField(
            model_name='paybyaccount',
            name='receipt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Resident.Receipt'),
        ),
        migrations.AddField(
            model_name='account',
            name='resident',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Resident.Resident'),
        ),
    ]
