# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MyUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_count', models.IntegerField()),
                ('car_count', models.IntegerField()),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MyUser.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='resident',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Resident.Unit'),
        ),
    ]
