# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0002_auto_20170811_1944'),
        ('Resident', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.IntegerField()),
                ('resident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Resident.Resident')),
            ],
        ),
        migrations.CreateModel(
            name='PayByAccount',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Resident.Account')),
            ],
        ),
        migrations.CreateModel(
            name='PayByBank',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cost', models.IntegerField(null=True)),
                ('event_cost', models.IntegerField(null=True)),
                ('facility_cost', models.IntegerField(null=True)),
                ('common_bills_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('reserve_date', models.DateTimeField(primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('use_date', models.DateTimeField()),
                ('cost', models.IntegerField()),
                ('state', models.CharField(choices=[('R', 'رد شده'), ('NC', 'بررسی نشده'), ('A', 'تایید شده')], max_length=1)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MySite.Facility')),
                ('resident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Resident.Resident')),
            ],
        ),
        migrations.AddField(
            model_name='paybybank',
            name='receipt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Resident.Receipt'),
        ),
        migrations.AddField(
            model_name='paybybank',
            name='resident',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Resident.Resident'),
        ),
        migrations.AddField(
            model_name='paybyaccount',
            name='receipt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Resident.Receipt'),
        ),
    ]
