# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0003_auto_20170813_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='state',
            field=models.CharField(choices=[('A', 'تایید شده'), ('R', 'رد شده'), ('NC', 'بررسی نشده')], max_length=2),
        ),
    ]
