# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 17:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0004_auto_20170813_0210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve',
            old_name='use_date',
            new_name='use_startDate',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='duration',
        ),
        migrations.AddField(
            model_name='reserve',
            name='use_finishDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 24, 17, 37, 9, 93096, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserve',
            name='state',
            field=models.CharField(choices=[('A', 'تایید شده'), ('NC', 'بررسی نشده'), ('R', 'رد شده')], max_length=2),
        ),
    ]
