# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(default='../static/images/user_profile_female.jpg', upload_to='static/images/profile_picture'),
        ),
    ]
