# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 11:34
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MyUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_num', models.IntegerField()),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MyUser.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('subject', models.CharField(
                    choices=[('E', 'خطا در سامانه'), ('S', 'پیشنهاد امکانات جدید یا تغییر'), ('Q', 'سوال و راهنمایی'),
                             ('C', 'شکایات'), ('O', 'سایر')], max_length=1)),
                ('text', models.TextField()),
                ('state', models.CharField(choices=[('W', 'در صف انتظار'), ('C', 'بررسی شده')], max_length=2)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.Manager')),
            ],
        ),
    ]
