# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('subject', models.CharField(choices=[('E', 'خطا در سامانه'), ('S', 'پیشنهاد امکانات جدید یا تغییر'), ('Q', 'سوال و راهنمایی'), ('C', 'شکایات'), ('O', 'سایر')], max_length=1)),
                ('text', models.TextField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.Manager')),
            ],
        ),
    ]
