# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0002_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='state',
            field=models.CharField(choices=[('W', 'در صف انتظار'), ('C', 'بررسی شده')], default='W', max_length=2),
            preserve_default=False,
        ),
    ]
